import { type NextPage } from "next";
import Head from "next/head";

import { SignInButton, useUser } from "@clerk/nextjs";
import { Loading } from "../components/Loading";

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";


dayjs.extend(relativeTime);

const CreateRocketWizard = () => {

  const { user } = useUser();
  if (!user) return null

  return (
    <div className="flex gap-3 w-full" >
      <Image src={user.profileImageUrl} alt="profile image"
        className="w-14 h-14 rounded-full"
        width={56}
        height={56}
        placeholder="blur"
        blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAA"
      />
      <input type="text" placeholder="type name of rocket" className="bg-transparent grow outline-none" />
    </div>
  )

}

type RocketWithUser = RouterOutputs["rockets"]["getAll"][number];

const RocketView = (props: RocketWithUser) => {
  const { rocket, author } = props;
  return (
    <div className="border-b border-slate-400 p-4 flex gap-3" key={rocket.id}>
      <Image
        width={56}
        height={56}
        placeholder="blur"
        blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAA"
        src={author.profilePicture} alt="profile image" />
      <div className="flex flex-col">
        <div className="flex text-slate-400 font-bold gap-2">
          <span>{`@${author.name}`}</span>
          <span className=" font-thin">{`· ${dayjs(rocket.createdAt).fromNow()}`}</span>
        </div>
        <span>{rocket?.description}</span>
      </div>
    </div>
  )

}

const Feed = () => {
  const { data, isLoading: rocketLoading } = api.rockets.getAll.useQuery();

  if (rocketLoading) return <Loading />
  
  if (!data) return <div>Something goes wrong!</div>

  return (
    <div>
      {[...data]?.map((rocketDetail) => (
        <RocketView {...rocketDetail} key={rocketDetail.rocket.id} />
      ))}
    </div>
  )
}
const Home: NextPage = (props) => {

  const { user, isLoaded: userLoaded, isSignedIn } = useUser();

  // start fetching data from the api on initial render
  const { data } = api.rockets.getAll.useQuery();

  // return empty div if user is not loaded
  if (!userLoaded) return <div />

  return (
    <>
      <Head>
        <title>Sora Union</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className=" w-full md:max-w-2xl h-full border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn && (<div className="flex justify-center">
              <SignInButton />
            </div>
            )}
            {!!isSignedIn && <CreateRocketWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
