import { type NextPage } from "next";
import Head from "next/head";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
const Home: NextPage = (props) => {

  const user = useUser();
  const { data } = api.rockets.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Sora Union</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          {!user.isSignedIn && <SignInButton>Sign in with Clerk </SignInButton>}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
          {data?.map((rocket) => (
            <div key={rocket?.id}>
              <p>{rocket?.description}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
